name: petmeals_local
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # packages
  provider: ^6.0.5
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # plugins
  cached_network_image: ^3.2.3
  day_night_time_picker: ^1.3.0+1
  easy_mask: ^2.0.1
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  # get_storage: ^2.1.1 #se va
  google_fonts: 6.1.0
  # google_mobile_ads: ^5.1.0
  go_router: ^11.1.2
  # google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  path_provider: ^2.1.3
  logger: ^2.0.2+1
  lottie: ^3.0.0
  time_parser: ^1.2.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/pet.png"
  adaptive_icon_background: "assets/logo/pet.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/logo/
    - assets/images/icons_att/
    - assets/images/icons/
    - assets/mypets/
    - .env